name: eduguide
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.5
  curved_navigation_bar: ^1.0.6
  flutter_speed_dial: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_animated_icon_button: ^1.1.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Profile3.png"
  min_sdk_android: 21
  windows:
    generate: true
    images_path: "assets/images/Profile3.png"
    icon_size: 48

flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/LogoEG.png
    - assets/images/owl.png
    - assets/images/Profile1.png
    - assets/images/Profile2.png
    - assets/images/LogoEGhome.png
